class DatabaseAlreadyOpenException implements Exception{}
class UnableToGetDocumetsDirectory implements Exception{}
class DatabaseIsNotOpen implements Exception{}
class CouldNotDeleteUser implements Exception{}
class UserAlreadyExist implements Exception{}
class CouldNotFindUser implements Exception{}
class CouldNotDeleteNote implements Exception{}
class CouldNotFindNotes implements Exception{}
class CouldNotUpdateNote implements Exception{}
class UserShouldBeSetBeforeReadingAllNotes implements Exception{}
